### ISSUE TITLE
Add Flash Context properties

### ISSUE THREAD

**Issue by ephraimtabackman** [snowplow/snowplow-actionscript3-tracker#5] opened 2015-01-06 12:07 UTC
Should we passively track certain Flash environment properties?

**Comment by alexanderdean** [comment] 2015-01-06 12:08
If so, we can create a JSON Schema for these properties like we have for mobile: https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.snowplow/mobile_context/jsonschema/1-0-0

**Comment by ephraimviewbix** [comment] 2015-01-12 13:07
We added these which we can add to the JSON Schema:

		public static const FLASH_PLAYER_TYPE:String = "fl_pt";
		public static const FLASH_VERSION:String = "fl_v";
		public static const FLASH_STAGE_SIZE:String = "fl_sz";
		public static const FLASH_IS_DEBUGGER:String = "fl_dbg";
		public static const FLASH_HAS_LOCAL_STORAGE:String = "fl_ls";
		public static const FLASH_HAS_JAVASCRIPT_ACCESS:String = "fl_ja";

**Comment by ephraimviewbix** [comment] 2015-01-12 13:26
I have created this Schema file. How do I submit it?

**Comment by alexanderdean** [comment] 2015-01-12 13:31
Hi @ephraimviewbix - awesome, please create a PR into this project: https://github.com/snowplow/iglu-central

**Comment by alexanderdean** [comment] 2015-01-12 14:21
This is here now: https://github.com/snowplow/iglu-central/pull/107/files

Here is how the iOS Tracker adds the context in: https://github.com/snowplow/snowplow-ios-tracker/blob/master/Snowplow/SnowplowTracker.m#L96

**Comment by natilivni** [comment] 2015-01-13 09:08
@ephraimtabackman, has this been uploaded to Iglu?  @yalisassoon, if it has not, can you give us instructions on how to get this schema live so we can test it using the astracker.snplow.com host?

**Comment by alexanderdean** [comment] 2015-01-13 09:09
Hey @natilivni - I will upload it now...

**Comment by alexanderdean** [comment] 2015-01-13 09:10
Actually it will take a little while - there's a couple of other assets that need creating too...

**Comment by ephraimtabackman** [comment] 2015-01-13 09:40
Yes, the schema is on Iglu.

**Comment by natilivni** [comment] 2015-01-13 09:41
Thanks @alexanderdean!  BTW, there is another piece of the puzzle I don't quite understand yet.  In the emails between Dani and @yalisassoon regarding why our events are not getting through, it said:

"you'll need to pass this data into Snowplow as base64 encoded JSON, using
the co parameter in the tracker protocol. Our documentation on this isn't
great - I think the example event dictionary".

Is this specific to GET requests?  I checked all our unit tests and they all seem to be POST requests.  I will add some unit test that test the GET method as well, but is the above also necessary for POST?

**Comment by alexanderdean** [comment] 2015-01-13 09:46
Hey @natilivni - if we're talking about the flash_context, then yes this needs to be added to the co/cx parameter. This is the same whether you're sending a POST or a GET - the difference is that if you are sending a GET, you with end up with `&co=[[user-defined contexts + flash_context]]`, whereas with POST you will be posting have a JSON envelope containing N events, each of which will contain "co": [[user-defined contexts + flash_context]].

It's a little confusing but in short: add the flash_context to your array of user defined contexts and the tracker will do the rest for you...

**Comment by alexanderdean** [comment] 2015-01-13 11:13
@natilivni , @ephraimtabackman - how do these column definitions (varchar sizes in particular) look to you: https://github.com/snowplow/snowplow/blob/feature/as-support/4-storage/redshift-storage/sql/com.snowplowanalytics.snowplow/flash_context_1.sql#L31 ?

**Comment by natilivni** [comment] 2015-01-13 12:52
@alexanderdean, I don't think that stage_size needs 255, 20 should be sufficient.  Everything else seems fine.

**Comment by alexanderdean** [comment] 2015-01-13 14:00
No problem @natilivni - I can resize. Could you give me an idea of what kind of data will sit in stage_size so I can determine the optimal compression?

**Comment by ephraimtabackman** [comment] 2015-01-13 14:31
@alexanderdean - stage_size is modeled after Parameter.RESOLUTION ("res") and Parameter.VIEWPORT ("vp") which are integer pairs delimited with a lowercase "x".

**Comment by alexanderdean** [comment] 2015-01-13 14:33
Ah gotcha - in that case, current compression should be fine. But are you sure you don't want to send this as two separate fields for easier analysis?

**Comment by alexanderdean** [comment] 2015-01-13 14:34
Or send as "stage_size": {"height": xxx, "width": yyy}, we can still put this into two integer fields in Redshift...

**Comment by ephraimtabackman** [comment] 2015-01-13 14:36
I agree that two separate fields is better for easier analysis. What is the reason that Viewport and Resolution are not separate fields?

**Comment by alexanderdean** [comment] 2015-01-13 14:37
Legacy - we were following the Google Analytics and Piwik approaches. We have to have dedicated code in the Snowplow enrichment process to unpick these into height and widths: https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/EnrichmentManager.scala#L139

**Comment by ephraimtabackman** [comment] 2015-01-13 14:38
So separate fields is preferable. I'll change it. Which do you prefer: two fields, or one field with two child fields?

**Comment by alexanderdean** [comment] 2015-01-13 14:38
I like 1 field with 2 child fields as it groups the stage entity better...

**Comment by ephraimtabackman** [comment] 2015-01-13 14:41
OK, will do. Do I make the changes on my feature/flash-context fork, or is that fork expired and I need to fork again?

**Comment by alexanderdean** [comment] 2015-01-13 14:41
Probably delete and re-fork will be fastest

**Comment by ephraimtabackman** [comment] 2015-01-13 14:42
OK. Learning best practices for GIT.

**Comment by ephraimtabackman** [comment] 2015-01-13 14:49
Is convention to copy the previous schema and increment the version number to 1-0-1 or leave it at 1-0-0 for this kind of change?

**Comment by alexanderdean** [comment] 2015-01-13 14:51
This is a patch - so we'll overwrite the existing...

A

On Tue, Jan 13, 2015 at 2:49 PM, Ephraim Tabackman <notifications@github.com
> wrote:

> Is convention to copy the previous schema and increment the version number
> to 1-0-1 or leave it at 1-0-0 for this kind of change?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snowplow/snowplow-actionscript3-tracker/issues/5#issuecomment-69754722>
> .
>



-- 
Co-founder
Snowplow Analytics <http://snowplowanalytics.com/>
The Roma Building, 32-38 Scrutton Street, London EC2A 4RQ, United Kingdom
+44 (0)203 589 6116
+44 7881 622 925
@alexcrdean <https://twitter.com/alexcrdean>

**Comment by alexanderdean** [comment] 2015-01-13 15:08
At the moment all properties in the JSON are optional @ephraimtabackman. Is that by design? You can make any required by setting the required: [] at the bottom of the JSON Schema.

**Comment by ephraimtabackman** [comment] 2015-01-13 15:15
Good question. I had thought about that and originally didn't see why any should be required, but looking at mobile_context I see there a few required there. 

How would you decide that? Depends on the needs of the developer.

Maybe just version...

**Comment by alexanderdean** [comment] 2015-01-13 15:16
Best way to decide is: are you 100% confident that all environments will be able to send one of the fields? If so, make that one required. If not, it's fine to leave it as is! I will update the Redshift table (remove the `not null` constraints)...

**Comment by ephraimtabackman** [comment] 2015-01-13 15:17
All fields are 100% available except stageSize. I will update.

**Comment by alexanderdean** [comment] 2015-01-13 15:18
Okay sounds good... So just leave stageSize out of the top-level required: []

**Comment by ephraimtabackman** [comment] 2015-01-13 16:12
All done and pushed. No need for a new PR?

**Comment by alexanderdean** [comment] 2015-01-13 16:13
Looks great - no need for a new PR. I have everything I need now - leave it with me, I will ping back later...

**Comment by alexanderdean** [comment] 2015-01-14 09:43
This is done now:

* Schema uploaded to Iglu Central
* JSON Path file being synced to all hosted asset buckets
* Redshift table definition `com_snowplowanalytics_snowplow_flash_context_1` deployed into the astracker test database

Closing this ticket now - please let me know as/when you see any flash_contexts landing in Redshift...

**Closed by alexanderdean** 2015-01-14 09:43 UTC
